# Generated by Django 4.1.3 on 2022-11-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostitems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
