# Generated by Django 4.1.3 on 2022-11-05 11:44

from django.db import migrations, models
import lostitems.models


class Migration(migrations.Migration):

    dependencies = [
        ('lostitems', '0002_alter_lostitem_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['created_at', 'question']},
        ),
        migrations.AlterModelOptions(
            name='guess',
            options={'ordering': ['created_at', 'user']},
        ),
        migrations.AlterModelOptions(
            name='lostitem',
            options={'ordering': ['-created_at', 'title']},
        ),
        migrations.AddField(
            model_name='lostitem',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=lostitems.models.upload_to),
        ),
    ]
