# Generated by Django 4.1.3 on 2022-11-05 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_question_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['category', 'title']},
        ),
    ]
